<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_MC Impact</name>
   <tag></tag>
   <elementGuidId>5d931662-728e-4f43-a20f-6216e6070e3e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='networkDetector']/div/div/div/div/div/div/div/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.project-title</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>2fb4291e-7fea-45f9-8b4d-40268029d83b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>project-title</value>
      <webElementGuid>212816d4-b224-419f-91cf-254c5bb3b55a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>MC Impact</value>
      <webElementGuid>5bf9edff-1ab7-426f-8634-ffef0e6b650f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;networkDetector&quot;)/div[@class=&quot;App&quot;]/div[1]/div[1]/div[@class=&quot;project-header engineering-execution&quot;]/div[@class=&quot;project-topbar&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;left-section col-md-3&quot;]/div[@class=&quot;project-title&quot;]</value>
      <webElementGuid>ae2d5366-43c2-4f12-967f-5bd2a70265f7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='networkDetector']/div/div/div/div/div/div/div/div[2]</value>
      <webElementGuid>3dca1f19-e8ee-4977-a82b-aa5ea7a44bf8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Engineering Execution'])[1]/following::div[1]</value>
      <webElementGuid>f267a73a-185a-4c30-9f85-7939cd71740e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SD'])[1]/following::div[8]</value>
      <webElementGuid>79e510af-faf5-4af0-91f1-f9a4a1886164</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My Project Home'])[1]/preceding::div[3]</value>
      <webElementGuid>54c8211a-5587-4720-bb48-0932003cb86c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Project Dashboard'])[1]/preceding::div[6]</value>
      <webElementGuid>81fb3d88-6ef8-41de-8df5-d6e12a8815bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='MC Impact']/parent::*</value>
      <webElementGuid>c06ffafa-43e6-4681-bd4a-c8529b035107</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/div/div/div/div/div[2]</value>
      <webElementGuid>f388d5bb-8d9b-4c1c-b728-f6173402ed72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'MC Impact' or . = 'MC Impact')]</value>
      <webElementGuid>cc0b691a-afa3-42f8-820c-efe5ee061976</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
