<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Engineering Execution</name>
   <tag></tag>
   <elementGuidId>cd03a683-a79d-4336-9b06-5d5870889f0f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='networkDetector']/div/div/div/div/div/div/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.project-topbar-title</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>9e08cac5-1e5e-4b7c-8693-99eeb5135f2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>project-topbar-title</value>
      <webElementGuid>7308b8af-c944-4b0f-954f-cf0ea557b9d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Engineering Execution</value>
      <webElementGuid>ded797a0-60de-44f0-bd3d-61624f18f476</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;networkDetector&quot;)/div[@class=&quot;App&quot;]/div[1]/div[1]/div[@class=&quot;project-header engineering-execution&quot;]/div[@class=&quot;project-topbar&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;left-section col-md-3&quot;]/div[@class=&quot;project-topbar-title&quot;]</value>
      <webElementGuid>cb27feb5-5931-4102-bc04-94dd735f88c5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='networkDetector']/div/div/div/div/div/div/div/div</value>
      <webElementGuid>abad9812-1ec2-41fe-bbb7-a5331ff5f133</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SD'])[1]/following::div[7]</value>
      <webElementGuid>48689fee-3a86-45be-9b7c-23858d0d3fad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MC Impact'])[1]/preceding::div[1]</value>
      <webElementGuid>ddec724b-4acb-4a52-8423-1b60f6ed13b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My Project Home'])[1]/preceding::div[4]</value>
      <webElementGuid>425a9e8e-e792-4f24-a62f-7bc9963995ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Engineering Execution']/parent::*</value>
      <webElementGuid>2ec30985-065d-48b9-a4f4-a9f331c156b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/div/div/div/div/div</value>
      <webElementGuid>55f36222-0a7f-44e5-9bae-ac63751ad29e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Engineering Execution' or . = 'Engineering Execution')]</value>
      <webElementGuid>ed6e1b91-5d50-4a2c-891d-4a6d106ea135</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
