<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Setup in Progress_searchRefAfter</name>
   <tag></tag>
   <elementGuidId>5cde0e88-36f0-4dfa-910a-6ce0546805c8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.searchRefAfter</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='networkDetector']/div/div/div/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>bcd7a8b6-b8c5-4178-843a-4362d2f2ea37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>search-icon</value>
      <webElementGuid>f2fd3b8c-c7fa-41ba-b2ce-ce5f47b408b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>searchRefAfter</value>
      <webElementGuid>acf05595-5cb1-4a93-ad29-37b36be87ec5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/static/media/search.ddf5b17f.svg</value>
      <webElementGuid>0eda581b-46e3-434e-8bb9-d26de807a330</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>ad3f813d-ec18-4995-aa64-f54296a3f17b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;networkDetector&quot;)/div[@class=&quot;App&quot;]/div[@class=&quot;container-fluid px-4 landingContainer&quot;]/div[@class=&quot;project-category&quot;]/div[@class=&quot;d-flex  align-items-center px-1 mb-2&quot;]/div[@class=&quot;search-container&quot;]/img[@class=&quot;searchRefAfter&quot;]</value>
      <webElementGuid>9e292d12-b5b6-4966-92e0-dabe8f29e513</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='networkDetector']/div/div/div/div/div/img</value>
      <webElementGuid>8312c4ca-fd16-4a17-abd3-e2aa40ac3a17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='search-icon']</value>
      <webElementGuid>a7a786a7-eb09-44e3-8630-51c9ea44b93a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/img</value>
      <webElementGuid>67db5bdc-4142-4a5c-8280-7c540b8ae45d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'search-icon' and @src = '/static/media/search.ddf5b17f.svg']</value>
      <webElementGuid>1d959e1c-844c-419f-9542-ed397732a425</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
