<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_123098</name>
   <tag></tag>
   <elementGuidId>631ef968-798a-408b-a2a1-28ecbc6c1e7b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>p.project-id</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='networkDetector']/div/div/div/div[2]/div/div/div/div/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>aaafc865-1b22-4548-aa7a-87ac3ae08c8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>project-id</value>
      <webElementGuid>d648f393-cfc0-4e1d-96f5-65808763a1bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>123098</value>
      <webElementGuid>ac67b276-a869-4a1d-8350-2000dcf908bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;networkDetector&quot;)/div[@class=&quot;App&quot;]/div[@class=&quot;container-fluid px-4 landingContainer&quot;]/div[@class=&quot;project-category&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-3 col-sm-6 col-xs-12 landingProjectCards&quot;]/div[@class=&quot;card landingcard&quot;]/div[@class=&quot;project-card-wrapper&quot;]/div[@class=&quot;card-body&quot;]/p[@class=&quot;project-id&quot;]</value>
      <webElementGuid>956a92ad-801e-4e04-ade8-ea9b14dcf2eb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='networkDetector']/div/div/div/div[2]/div/div/div/div/p</value>
      <webElementGuid>439d51e9-ff34-4eaa-a73f-4ebe8ad2a23c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Setup in Progress'])[1]/following::p[1]</value>
      <webElementGuid>b8157cb3-85c5-47bd-afa0-5788574e5451</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ED'])[1]/following::p[1]</value>
      <webElementGuid>f78b3d48-5287-436c-bf1e-5f3c9451b5b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Engineering Execution'])[1]/preceding::p[3]</value>
      <webElementGuid>6649fa27-011a-4bcf-9d83-bc6d8f65b590</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Previous'])[1]/preceding::p[27]</value>
      <webElementGuid>1fdb2843-4c53-4f29-8d33-43dd1240cb0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='123098']/parent::*</value>
      <webElementGuid>8128bde2-cbb4-41ca-8f8b-ebf39498815d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p</value>
      <webElementGuid>ae36f890-4389-4841-a865-49f4f68dc531</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = '123098' or . = '123098')]</value>
      <webElementGuid>b0889469-4d80-4e75-a78d-d4ea0e25d584</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
