<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_79610</name>
   <tag></tag>
   <elementGuidId>5ca7370e-05af-4a7c-9afa-4e812d0c97d0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='networkDetector']/div/div/div[2]/div[2]/div/div/div/div/p</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>1657cc0b-ad87-4d86-84cb-6550480b93a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>project-id</value>
      <webElementGuid>5dd3a1e3-0ac8-44ec-b91d-d3968ddb97de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>79610</value>
      <webElementGuid>d8bd6534-cec1-4dde-91e7-c0577398fc3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;networkDetector&quot;)/div[@class=&quot;App&quot;]/div[@class=&quot;container-fluid px-4 landingContainer&quot;]/div[@class=&quot;project-category&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-3 col-sm-6 col-xs-12 landingProjectCards&quot;]/div[@class=&quot;card landingcard&quot;]/div[@class=&quot;project-card-wrapper&quot;]/div[@class=&quot;card-body&quot;]/p[@class=&quot;project-id&quot;]</value>
      <webElementGuid>8cd7c2ab-8d6b-4338-9d94-71ba9055fdd3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='networkDetector']/div/div/div[2]/div[2]/div/div/div/div/p</value>
      <webElementGuid>dea285bc-306f-4237-b4d9-692110591f8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Engineering Execution'])[1]/following::p[1]</value>
      <webElementGuid>193cf1d2-ed22-41bb-ac18-d7810225d68f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Next'])[1]/following::p[1]</value>
      <webElementGuid>b869a96d-92c9-4145-85f8-8c24a9083dcd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='79610']/parent::*</value>
      <webElementGuid>b91fc03b-e8b2-49f4-bd04-814fedf3e784</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/div/div/p</value>
      <webElementGuid>88fbfdfc-8609-4015-85ce-c0c42e846026</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = '79610' or . = '79610')]</value>
      <webElementGuid>bf915540-0651-4e95-bb21-d3108375df13</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
