<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Foundation List</name>
   <tag></tag>
   <elementGuidId>e93aed7b-5a93-4dd6-a0ea-4b27c498566e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='networkDetector']/div/div/div/div[2]/div[2]/div/div/div/div[3]/div/div/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.formHeader</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>6b331284-60f4-42ab-af82-1dc668fa9935</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>formHeader</value>
      <webElementGuid>cd20198c-826e-4b21-a51d-1a1ebcc525d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Foundation List</value>
      <webElementGuid>c465ddd3-1c67-44f1-b36e-cb389d9ed9c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;networkDetector&quot;)/div[@class=&quot;App&quot;]/div[1]/div[1]/div[@class=&quot;dashboard-view project-input-output&quot;]/div[@class=&quot;tab-content container-fluid no-pad-tab&quot;]/div[@class=&quot;tab-pane row fade show active&quot;]/div[@class=&quot;project-common-container with-fixed-action-bar&quot;]/div[@class=&quot;project-common-sub-container editor-mode-view&quot;]/div[@class=&quot;emv-details&quot;]/div[@class=&quot;ca-detailed centre-section-min-width&quot;]/div[@class=&quot;d-flex align-items-center header-block&quot;]/span[@class=&quot;formHeader&quot;]</value>
      <webElementGuid>e6e2bdd3-31d9-4276-a349-5d773cf6b4ac</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='networkDetector']/div/div/div/div[2]/div[2]/div/div/div/div[3]/div/div/span</value>
      <webElementGuid>d0fb10e6-779e-4e41-b1b6-17eb58f396c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mechanical Equipment List'])[1]/following::span[1]</value>
      <webElementGuid>afa5cee7-0c07-4918-a7cf-4887a2e42457</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EQUIPMENT'])[1]/following::span[2]</value>
      <webElementGuid>fd77b1c9-cff3-4471-bea8-3883b9c053d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Not Applicable'])[1]/preceding::span[1]</value>
      <webElementGuid>f968e496-0e44-40bc-8e5f-ef53ecb19e12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Foundation Tag'])[1]/preceding::span[1]</value>
      <webElementGuid>68242080-1bf2-4ff4-871e-70d5e8440fb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/span</value>
      <webElementGuid>b75bbfaf-4449-4524-9280-288bd763d8d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Foundation List' or . = 'Foundation List')]</value>
      <webElementGuid>7b72e7c4-d296-4e89-8702-83d80da75d22</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
